name: Build and Deploy Application

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Replace with your required Node.js version

      # Step 3: Set npm registry to JFrog Artifactory and authenticate
      - name: Configure npm to use JFrog Artifactory
        run: |
          # Set the npm registry to point to JFrog Artifactory npm repository
          npm config set registry https://pkhostingltd.jfrog.io/artifactory/api/npm/eai-uac-npm-virtual/
          
          # Set up authentication using API token stored in GitHub Secrets
          echo "https://pkhostingltd.jfrog.io/artifactory/api/npm/eai-uac-npm-virtual/:_authToken=${{ secrets.JFROG_API_TOKEN }}" > ~/.npmrc

      # Step 4: Install npm dependencies from JFrog Artifactory
      - name: Install npm dependencies
        run: npm install
        
      # Step 5: Build the application and check the output directory
      - name: Build Application
        run: |
          npm run build
          ls -al   # Check if the dist/ directory contains the build files
      
      - name: Publish Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: '${{ env.appName }}-artifact'
          path: dist/  # Assuming this is the output directory
